### ISSUE TITLE
"rrln" command fails on IDA 7.0

### ISSUE THREAD

**Issue by Gbps** [bootleg/ret-sync#37]
```python
Traceback (most recent call last):
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/plugins/SyncPlugin.py", line 824, in cb_broker_on_out
    self.worker.parse_exec(req.strip())
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/plugins/SyncPlugin.py", line 614, in parse_exec
    req_handler(hash)
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/plugins/SyncPlugin.py", line 386, in req_rrln
    addr = idc.get_name_ea_simple(sym)
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python/idc.py", line 1888, in get_name_ea_simple
    return ida_name.get_name_ea(BADADDR, name)
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python/ida_name.py", line 258, in get_name_ea
    return _ida_name.get_name_ea(*args)
TypeError: in method 'get_name_ea', argument 2 of type 'char const *'
```

This is because the IDAPython 2.7 api can't convert type `unicode` to `str` implicitly from the api level.

This can be resolved at SyncPlugin.py:385
```python
 addr = idc.get_name_ea_simple(sym)
```
to
```python
 addr = idc.get_name_ea_simple(str(sym))
```

Thanks!

**Comment by bootleg** [comment]
https://github.com/bootleg/ret-sync/commit/792af4895af0f9fe56e6ae2056417ef981ea03d8
