### ISSUE TITLE
x64dbg running '!cmt chinese' command the plug-in to crash

### ISSUE THREAD

**Issue by Kei0725** [bootleg/ret-sync#68]
IDA  version: 7.5
python version: 3.8.5

x64dbg : !cmt 中文

IDA output window:
```
---------------------------------------------------------------------------------------
[sync] default idb name: 4_3.exe
[sync] sync enabled
[sync] cmdline: "C:\ProgramData\Anaconda3\python.exe" -u "D:\Program Files\IDA\IDA_Pro_v7.5\plugins\retsync\broker.py" --idb "4_3.exe"
[sync] module base 0x400000
[sync] hexrays #7.5.0.201028 found
[sync] broker started
[sync] plugin loaded
[sync] << broker << dispatcher not found, trying to run it
[sync] << broker << dispatcher now runs with pid: 16028
[sync] << broker << connected to dispatcher
[sync] << broker << dispatcher msg: add new client (listening on port 31734), nb client(s): 1
[sync] << broker << dispatcher msg: new debugger client: dbg connect - x64_dbg
[sync] set debugger dialect to x64_dbg, enabling hotkeys
[sync] idb is enabled
Traceback (most recent call last):
  File "D:/Program Files/IDA/IDA_Pro_v7.5/plugins/SyncPlugin.py", line 831, in cb_broker_on_out
    buffer = rs_decode(self.readAllStandardOutput().data())
  File "D:/Program Files/IDA/IDA_Pro_v7.5/plugins\retsync\rsconfig.py", line 170, in rs_decode
    return buffer_bytes.decode(RS_ENCODING)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 27: invalid continuation byte
````

**Comment by bootleg** [comment]
HI @Kei0725, 

I'll look into it asap. 
thanks for reporting it.

**Comment by bootleg** [comment]
Got it working here. Could you please confirm if it is ok for you ? 

There may still be default code page issue I'm not aware of.
Cheers,

**Comment by Kei0725** [comment]
thx, now it works   👍
